# Generated by Django 3.2.4 on 2021-07-20 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('qna', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qnacomment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qna_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qna',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='qnas', to='product.product'),
        ),
        migrations.AddField(
            model_name='qna',
            name='qna_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='qnas', to='qna.qnacategory'),
        ),
        migrations.AddField(
            model_name='qna',
            name='qna_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='qnas', to='qna.qnastatus'),
        ),
        migrations.AddField(
            model_name='qna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qnas', to=settings.AUTH_USER_MODEL),
        ),
    ]
