# Generated by Django 3.2.4 on 2021-07-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
    ]
