# Generated by Django 3.2.4 on 2021-07-21 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_qna_is_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnacomment',
            old_name='staff',
            new_name='user',
        ),
    ]
