# Generated by Django 3.2.4 on 2021-07-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_rename_staff_qnacomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
