# Generated by Django 3.2.4 on 2021-07-23 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderedproduct_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipment_number',
            new_name='shipment_memo',
        ),
    ]
