# Generated by Django 3.2.4 on 2021-07-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_shipment_number_order_shipment_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_memo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
